window:
  startup_mode: Fullscreen
  padding:
    x: 3
    y: 3
font:
  size: 18.0
  use_thin_strokes: true
shell:
 program: /bin/zsh
 args:
 - -l
key_bindings:
  - { key: Key3,     mods: Alt, chars: "#"     }
